name: DragonForge Kingdoms
version: '${version}'
main: io.github.derec4.dragonforgekingdoms.DragonForgeKingdoms
api-version: '1.20'
authors: [Derex]
description: Framework for DragonForge Kingdoms server
